/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { apiEmployeeGet } from '../fn/employee/api-employee-get';
import { ApiEmployeeGet$Params } from '../fn/employee/api-employee-get';

@Injectable({ providedIn: 'root' })
export class EmployeeService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `apiEmployeeGet()` */
  static readonly ApiEmployeeGetPath = '/api/Employee';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiEmployeeGet()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiEmployeeGet$Response(params?: ApiEmployeeGet$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return apiEmployeeGet(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiEmployeeGet$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiEmployeeGet(params?: ApiEmployeeGet$Params, context?: HttpContext): Observable<void> {
    return this.apiEmployeeGet$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

}
