/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { apiOrderCustomerIdOrdersGet } from '../fn/order/api-order-customer-id-orders-get';
import { ApiOrderCustomerIdOrdersGet$Params } from '../fn/order/api-order-customer-id-orders-get';
import { apiOrderPost } from '../fn/order/api-order-post';
import { ApiOrderPost$Params } from '../fn/order/api-order-post';

@Injectable({ providedIn: 'root' })
export class OrderService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `apiOrderCustomerIdOrdersGet()` */
  static readonly ApiOrderCustomerIdOrdersGetPath = '/api/Order/{customerId}/orders';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiOrderCustomerIdOrdersGet()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiOrderCustomerIdOrdersGet$Response(params: ApiOrderCustomerIdOrdersGet$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return apiOrderCustomerIdOrdersGet(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiOrderCustomerIdOrdersGet$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiOrderCustomerIdOrdersGet(params: ApiOrderCustomerIdOrdersGet$Params, context?: HttpContext): Observable<void> {
    return this.apiOrderCustomerIdOrdersGet$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

  /** Path part for operation `apiOrderPost()` */
  static readonly ApiOrderPostPath = '/api/Order';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiOrderPost()` instead.
   *
   * This method sends `application/*+json` and handles request body of type `application/*+json`.
   */
  apiOrderPost$Response(params?: ApiOrderPost$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return apiOrderPost(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiOrderPost$Response()` instead.
   *
   * This method sends `application/*+json` and handles request body of type `application/*+json`.
   */
  apiOrderPost(params?: ApiOrderPost$Params, context?: HttpContext): Observable<void> {
    return this.apiOrderPost$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

}
