/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { apiShipperGet } from '../fn/shipper/api-shipper-get';
import { ApiShipperGet$Params } from '../fn/shipper/api-shipper-get';

@Injectable({ providedIn: 'root' })
export class ShipperService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `apiShipperGet()` */
  static readonly ApiShipperGetPath = '/api/Shipper';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiShipperGet()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiShipperGet$Response(params?: ApiShipperGet$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return apiShipperGet(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiShipperGet$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiShipperGet(params?: ApiShipperGet$Params, context?: HttpContext): Observable<void> {
    return this.apiShipperGet$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

}
