/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export type { CustomerPredictionDto } from './models/customer-prediction-dto';
export type { OrderDetailDto } from './models/order-detail-dto';
export type { OrderDto } from './models/order-dto';
